# Generated by Django 4.2.23 on 2025-07-12 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='Unknown', max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('resident_address', models.TextField(default='Not Provided')),
                ('category', models.CharField(choices=[('Resident', 'Resident'), ('Visitor', 'Visitor'), ('Criminal', 'Criminal')], default='Resident', max_length=100)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('registered_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='Unknown', max_length=100)),
                ('vehicle_number', models.CharField(max_length=100, unique=True)),
                ('resident_address', models.TextField(default='Not Provided')),
                ('category', models.CharField(choices=[('Resident', 'Resident'), ('Visitor', 'Visitor'), ('Criminal', 'Criminal')], default='Resident', max_length=100)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
